# Generated by Django 5.2.6 on 2025-10-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_asset_code_asset_code_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='reserved_assets',
            field=models.ManyToManyField(blank=True, related_name='events_reserved_for', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.evento')),
            ],
        ),
    ]
