# Generated by Django 5.2.6 on 2025-10-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_checklistitem_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.evento'),
        ),
    ]
