# Generated by Django 5.2.6 on 2025-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_checklistitem_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(),
        ),
    ]
