# Generated by Django 5.2.6 on 2025-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_checklistitem_order_alter_checklistitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('active', 'Activo')], default='pending', max_length=20),
        ),
    ]
