# Generated by Django 5.2.6 on 2025-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_evento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('evento', 'Evento'), ('visita', 'Visita'), ('prestamo', 'Préstamo')], default='evento', max_length=10),
        ),
    ]
