# Generated by Django 5.2.6 on 2025-11-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_evento_visitante_evento_current_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='current_attendees',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='max_attendees',
        ),
    ]
