# Generated by Django 5.2.6 on 2025-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_evento_current_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='current_attendees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='max_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
