# Generated by Django 5.2.6 on 2025-11-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_completed_date_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
    ]
