# Generated by Django 5.2.6 on 2025-11-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenance_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type',
        ),
    ]
