# Generated by Django 5.2.6 on 2025-10-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetcategory_level_assetcategory_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, editable=False, help_text='Código único para el activo, generado automáticamente.', max_length=255, null=True, unique=True),
        ),
    ]
