# Generated by Django 5.2.6 on 2025-10-02 20:23

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la categoría.', null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Nombre del ícono (ej. 'fas fa-laptop').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory'),
        ),
    ]
