# Generated by Django 5.2.6 on 2025-10-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetcategory_description_assetcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'Categoría de Activo', 'verbose_name_plural': 'Categorías de Activos'},
        ),
    ]
