# Generated by Django 5.2.6 on 2025-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_assetcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_code',
        ),
        migrations.AddField(
            model_name='asset',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En uso'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20),
        ),
    ]
