# Generated by Django 5.2.6 on 2025-11-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_event_assetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='AssetRequest',
        ),
    ]
