# Generated by Django 5.2.6 on 2025-11-24 16:40

from django.db import migrations

def create_groups(apps, schema_editor):
    """
    Crea los grupos de usuarios por defecto (Admin, Staff, Tech).
    """
    Group = apps.get_model('auth', 'Group')
    group_names = ['administrador', 'tecnico', 'administrativo']
    for group_name in group_names:
        Group.objects.get_or_create(name=group_name)

def remove_groups(apps, schema_editor):
    """
    Elimina los grupos de usuarios creados por defecto.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['administrador', 'tecnico', 'administrativo']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0001_initial"),
        # Add dependency on the app that creates the Group model, which is 'auth'
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]