# Generated by Django 5.2.6 on 2025-11-10 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_loan_date_alter_loan_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 19, 42, 10, 728576, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
